kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.16
      minVersion: 4.16.42
      maxVersion: 4.16.42
    graph: true 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
      packages: 
       - name: aws-load-balancer-operator
       - name: node-observability-operator